app = "nr-lagos-api-staging"
primary_region = "lhr"

[build]
  dockerfile = "apps/api/Dockerfile"

[env]
  NODE_ENV = "production"
  APP_ENV = "staging"
  PORT = "3000"
  HOSTNAME = "0.0.0.0"
  AUTH_COOKIE_DOMAIN = ""

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[[http_service.checks]]
  interval = "15s"
  timeout = "5s"
  grace_period = "15s"
  method = "GET"
  path = "/health"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
