/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all Lagos locations with aliases
         * @description Public endpoint. Returns all supported Lagos pickup and drop-off locations.
         *     Each location has a canonical name and a list of aliases (common shorthands used by commuters).
         *
         *     Use these values to populate autocomplete in ride search. Both the canonical name
         *     and any alias are accepted in `GET /rides/search?from=&to=`.
         */
        get: operations["listLocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send SMS OTP to a phone number
         * @description Public endpoint. Starts login by requesting a one-time code for the given phone number.
         */
        post: operations["requestOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify OTP code and return token
         * @description Public endpoint. Exchanges a valid OTP code for a bearer token used on protected routes.
         */
        post: operations["verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update signed-in user's profile
         * @description Protected endpoint. Requires a Bearer token in the Authorization header.
         *
         *     Example header:
         *     `Authorization: Bearer token_user_001_1713722394`
         */
        post: operations["updateMe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find rides between two locations
         * @description Protected endpoint. Requires a Bearer token in the Authorization header. Partial, case-insensitive matches on `from` and `to` are supported (e.g. `yab` matches `Yaba`).
         */
        get: operations["searchRides"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the signed-in user's ride for today
         * @description Protected endpoint. Requires a Bearer token in the Authorization header.
         */
        get: operations["getTodayRide"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/{rideId}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record riding or skipping for today
         * @description Protected endpoint. Requires a Bearer token in the Authorization header.
         */
        post: operations["respondToRide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/{rideId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join a ride as a passenger
         * @description Protected endpoint. Requires a Bearer token in the Authorization header.
         */
        post: operations["joinRide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new ride
         * @description Protected endpoint. Requires a Bearer token in the Authorization header.
         */
        post: operations["createRide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/rides/rider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my ride bookings as a passenger
         * @description Protected endpoint. Requires a Bearer token in the Authorization header.
         */
        get: operations["getMyRiderRides"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/rides/driver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get rides I created
         * @description Protected endpoint. Requires a Bearer token in the Authorization header.
         */
        get: operations["getMyDriverRides"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rides/{rideId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Driver cancels a ride and all its bookings
         * @description Protected endpoint. Requires a Bearer token in the Authorization header.
         */
        delete: operations["cancelRide"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/rides/rider/{bookingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Passenger cancels their own booking
         * @description Protected endpoint. Requires a Bearer token in the Authorization header.
         */
        delete: operations["cancelBooking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            status?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        /**
         * @example {
         *       "id": "victoria_island",
         *       "name": "Victoria Island",
         *       "aliases": [
         *         "VI",
         *         "Eti-Osa"
         *       ],
         *       "description": "Premier business and nightlife district in Lagos, home to corporate headquarters and upscale restaurants."
         *     }
         */
        Location: {
            /**
             * @description Stable slug identifier (lowercase, underscored)
             * @example victoria_island
             */
            id: string;
            /**
             * @description Official full place name
             * @example Victoria Island
             */
            name: string;
            /**
             * @description Common shorthands and alternative names used by commuters
             * @example [
             *       "VI",
             *       "Eti-Osa"
             *     ]
             */
            aliases: string[];
            /**
             * @description Brief context about the area for riders who may be unfamiliar
             * @example Premier business and nightlife district in Lagos, home to corporate headquarters and upscale restaurants.
             */
            description: string;
        };
        /**
         * @example {
         *       "phone": "+2348012345678"
         *     }
         */
        OtpRequest: {
            /** @example +2348012345678 */
            phone: string;
        };
        /**
         * @example {
         *       "phone": "+2348012345678",
         *       "code": "1234"
         *     }
         */
        OtpVerifyRequest: {
            /** @example +2348012345678 */
            phone: string;
            /** @example 1234 */
            code: string;
        };
        /**
         * @example {
         *       "token": "token_user_001_1713722394",
         *       "phone": "+2348012345678"
         *     }
         */
        OtpVerifyResponse: {
            /** @example token_user_001_1713722394 */
            token?: string;
            /** @example +2348012345678 */
            phone?: string;
        };
        /**
         * @example {
         *       "error": "Unauthorized"
         *     }
         */
        ErrorResponse: {
            /** @example Unauthorized */
            error?: string;
        };
        /**
         * @example {
         *       "name": "Rasul Omeni",
         *       "company": "NaijaRides"
         *     }
         */
        MeUpdateRequest: {
            /** @example Rasul Omeni */
            name: string;
            /** @example NaijaRides */
            company?: string;
        };
        /**
         * @example {
         *       "name": "Rasul Omeni",
         *       "company": "NaijaRides"
         *     }
         */
        MeUpdateResponse: {
            /** @example Rasul Omeni */
            name?: string;
            /** @example NaijaRides */
            company?: string;
        };
        Ride: {
            id: string;
            from: string;
            to: string;
            /** @description Display time string (e.g. 7:30 AM) */
            time: string;
            /** @description Whole Naira amount */
            price: number;
            seatsTotal: number;
            seatsTaken: number;
            driverName: string;
            driverCompany?: string;
            /** @enum {string} */
            status: "active" | "cancelled" | "completed";
            repeatDays: ("Mon" | "Tue" | "Wed" | "Thu" | "Fri")[];
        };
        RideError: {
            error: string;
        };
        RideRespondRequest: {
            riding: boolean;
        };
        RideRespondResponse: {
            rideId: string;
            riding: boolean;
            /** @description ISO date (YYYY-MM-DD) */
            date: string;
        };
        JoinRideRequest: Record<string, never>;
        CreateRideRequest: {
            from: string;
            to: string;
            time: string;
            seats: number;
            price: number;
            repeatDays: ("Mon" | "Tue" | "Wed" | "Thu" | "Fri")[];
        };
        RiderBookingItem: {
            /** @description Booking id */
            id: string;
            from: string;
            to: string;
            time: string;
            driverName: string;
            /** @enum {string} */
            status: "active" | "cancelled" | "completed";
        };
        DriverRideItem: {
            /** @description Ride id */
            id: string;
            from: string;
            to: string;
            time: string;
            passengersCount: number;
            /** @enum {string} */
            status: "active" | "cancelled" | "completed";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listLocations: {
        parameters: {
            query?: {
                /**
                 * @description Filter by name or alias (case-insensitive substring match). Omit to return all locations.
                 * @example ike
                 */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All supported Lagos locations with aliases */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"][];
                };
            };
        };
    };
    requestOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequest"];
            };
        };
        responses: {
            /** @description OTP sent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerifyRequest"];
            };
        };
        responses: {
            /** @description Verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpVerifyResponse"];
                };
            };
            /** @description Invalid code */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeUpdateRequest"];
            };
        };
        responses: {
            /** @description Profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeUpdateResponse"];
                };
            };
            /** @description Profile updated (no body) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchRides: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching rides */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"][];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideError"];
                };
            };
        };
    };
    getTodayRide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ride for today or null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"] | null;
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideError"];
                };
            };
        };
    };
    respondToRide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RideRespondRequest"];
            };
        };
        responses: {
            /** @description Response recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideRespondResponse"];
                };
            };
            /** @description Response recorded (no body) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideError"];
                };
            };
        };
    };
    joinRide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRideRequest"];
            };
        };
        responses: {
            /** @description Joined ride */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"];
                };
            };
            /** @description Joined ride (no body) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideError"];
                };
            };
            /** @description Ride full or already joined */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideError"];
                };
            };
        };
    };
    createRide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRideRequest"];
            };
        };
        responses: {
            /** @description Ride created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ride"];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideError"];
                };
            };
        };
    };
    getMyRiderRides: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rider bookings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderBookingItem"][];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideError"];
                };
            };
        };
    };
    getMyDriverRides: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Driver rides */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverRideItem"][];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideError"];
                };
            };
        };
    };
    cancelRide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ride cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideError"];
                };
            };
            /** @description Not the driver */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideError"];
                };
            };
            /** @description Ride not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideError"];
                };
            };
        };
    };
    cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideError"];
                };
            };
            /** @description Not your booking */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideError"];
                };
            };
            /** @description Booking not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideError"];
                };
            };
        };
    };
}
